import { BugIndicatingError, onUnexpectedError } from "./errors";

/**
 * Asserts that a condition is `truthy`.
 *
 * @throws provided {@linkcode messageOrError} if the {@linkcode condition} is `falsy`.
 *
 * @param condition The condition to assert.
 * @param messageOrError An error message or error object to throw if condition is `falsy`.
 */
export function assert(
  condition: boolean,
  messageOrError: string | Error = "unexpected state",
): asserts condition {
  if (!condition) {
    // if error instance is provided, use it, otherwise create a new one
    const errorToThrow =
      typeof messageOrError === "string"
        ? new BugIndicatingError(`Assertion Failed: ${messageOrError}`)
        : messageOrError;

    throw errorToThrow;
  }
}

/**
 * condition must be side-effect free!
 */
export function assertFn(condition: () => boolean): void {
  if (!condition()) {
    // eslint-disable-next-line no-debugger
    debugger;
    // Reevaluate `condition` again to make debugging easier
    condition();
    onUnexpectedError(new BugIndicatingError("Assertion Failed"));
  }
}

export function checkAdjacentItems<T>(
  items: readonly T[],
  predicate: (item1: T, item2: T) => boolean,
): boolean {
  let i = 0;
  while (i < items.length - 1) {
    const a = items[i];
    const b = items[i + 1];
    if (!predicate(a, b)) {
      return false;
    }
    i++;
  }
  return true;
}
